### ISSUE TITLE
Error: BrowserModule has already been loaded

### ISSUE THREAD

**Issue by sc0tt5** [abdulkadirgenc/ng-wizard#1]
When the wizard exists in a sub-component (not app.component) and when lazy loading from the routing module, the BrowswerModule gets loaded twice causing the following error: 

> Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

**Comment by abdulkadirgenc** [comment]
Fixed.
