### ISSUE TITLE
Unable to hide Wizard Steps

### ISSUE THREAD

**Issue by tcbuzor** [abdulkadirgenc/ng-wizard#13]
There should be a way to hide a wizard step by either setting [hidden] = "true" or providing an array of hidden steps.
Currently, this functionality is missing or not documented.

**Comment by abdulkadirgenc** [comment]
Fixed. You can pass "state" parameter to step as in the sample below.
      <ng-wizard-step [title]="'Step 5'" [description]="'Step 5 description'" [state]="'hidden'">
        <span>Step 5 content</span>
      </ng-wizard-step>
