### ISSUE TITLE
[Feature Request] Go To Specific Step

### ISSUE THREAD

**Issue by amcpanaligan** [abdulkadirgenc/ng-wizard#15]
Hi @abdulkadirgenc ,

As I have seen here https://github.com/abdulkadirgenc/ng-wizard/blob/84d6566de1ba4d4e8960d6a3137e2aece457bcc1/src/ng-wizard/lib/core/wizard/ng-wizard.component.ts#L282

There is an internal `_showStep` function that is being utilized by the `next` and `previous` functions. My request is to expose it too from the `NgWizardService` so that components can go to pages that they need not just moving to next, and previous

**Comment by rohan2934** [comment]
+1

**Comment by amcpanaligan** [comment]
@rohan2934 none yet. Maybe we should just fork the repo and create a pull request

**Comment by abdulkadirgenc** [comment]
Hi guys,

I checked-in https://github.com/abdulkadirgenc/ng-wizard/commit/bf5b78d9a6fc9b5eea69aae9532afd6a3930f1e4
but not published yet.
