### ISSUE TITLE
How to enable or disable next button?

### ISSUE THREAD

**Issue by furflez** [abdulkadirgenc/ng-wizard#4]
I want to enable or disable if my form is completed and I can't figure out how.

**Comment by dalibor-sanzeru** [comment]
HI I am playing with this component just now.
This worked for me:

```
config: NgWizardConfig = {
    anchorSettings: {anchorClickable: false}
}
```

**Comment by xquitralx** [comment]
> HI I am playing with this component just now.
> This worked for me:
> 
> ```
> config: NgWizardConfig = {
>     anchorSettings: {anchorClickable: false}
> }
> ```

 config: NgWizardConfig = {
    selected: 0,
    theme: THEME.dots,
    anchorSettings: {anchorClickable: false},
    toolbarSettings: {
      toolbarExtraButtons: [
        { text: 'finish', class: 'btn btn-info', event: () => { this.emitMessage(this.quizWizardMessage.error("Envio resultado desafio no implementado")) } }
      ],
    },
    lang: { next: 'Next', previous: 'Previous' }
  };
  
  explain me
